Use optargs to extend ci-run for python3
LAVA-1071 - make it easier to run the python 3 unit tests for
the V2 support in ./ci-run

Change-Id: I414ea0236198a66329eb1a46a59265efa6c6ad56

diff --git a/ci-run b/ci-run
--- a/ci-run
+++ b/ci-run
@@ -3,8 +3,37 @@
 set -x
 set -e
 
+PEP8=1
+ALL=0
+
+while getopts ":pa" opt; do
+  case $opt in
+    p)
+      # pep8 only
+      PEP8=2
+      ;;
+    a)
+      # python3 and python2
+      ALL=1
+      ;;
+    \?)
+      echo "Usage:"
+      echo "-p - pep8 only"
+      echo "-a - run all tests: pep8, python2 and python3"
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+  esac
+done
+
+shift $((OPTIND -1))
+
 echo "Checking pep8"
 pep8 --ignore E501,E722 --exclude=".eggs/*" .
+
+if [ ${PEP8} = 2 ]; then
+    exit 0
+fi
 
 echo "Starting unit tests"
 echo
@@ -12,5 +41,8 @@ echo
 python setup.py test "$@"
 
 # to run python3 unit tests, you can use
-# python3 -m unittest discover -v lava_dispatcher.pipeline
 # but the python3 dependencies are not automatically installed.
+
+if [ ${ALL} = 1 ]; then
+    python3 -m unittest discover -v lava_dispatcher.pipeline
+fi
