drop use of sudo in postinst

diff --git a/debian/lava-server.postinst b/debian/lava-server.postinst
--- a/debian/lava-server.postinst
+++ b/debian/lava-server.postinst
@@ -33,7 +33,7 @@ then
 fi
 if [ "$LAVA_DB_PORT" = '$LAVA_DB_PORT' ]
 then
-  LAVA_DB_PORT=""
+  LAVA_DB_PORT=5432
 fi
 if [ "$LAVA_DB_PASSWORD" = '$LAVA_DB_PASSWORD' ]
 then
@@ -41,7 +41,10 @@ then
 fi
 LAVA_SYS_USER="$LAVA_DB_NAME"
 LAVA_SYS_HOME=/var/lib/lava-server/home/
-
+if [ "$LAVA_DB_PORT" = '' ]
+then
+  LAVA_DB_PORT=5432
+fi
 write_config() {
     cat <<INSTANCE_CONF
 # Config version
@@ -82,37 +85,16 @@ die() {
 install_database()
 {
     # Create database user, if it doesn't exist
-    if ! sudo -u postgres psql -c "SELECT usename FROM pg_user WHERE usename='$LAVA_DB_USER'" | grep "$LAVA_DB_USER"; then
-        sudo -u postgres createuser \
-            --no-createdb \
-            --encrypted \
-            --login \
-            --no-superuser \
-            --no-createrole \
-            --no-password \
-            --port "$LAVA_DB_PORT" \
-            "$LAVA_DB_USER" \
-            ||  "Failed to create database user"
+    if ! su postgres -c "psql \"-c SELECT usename FROM pg_user WHERE usename='$LAVA_DB_USER'\""; then
+        su postgres -c "createuser --no-createdb --encrypted --login --no-superuser --no-createrole --no-password --port $LAVA_DB_PORT $LAVA_DB_USER"|| "Failed to create database user"
     fi
 
     # Set a password for our new user
-    sudo -u postgres psql \
-        --port "$LAVA_DB_PORT" \
-        --quiet \
-        --command="ALTER USER \"$LAVA_DB_USER\" WITH PASSWORD '$LAVA_DB_PASSWORD'" \
-        || die "Failed to set database password"
+    su postgres -c "psql --port $LAVA_DB_PORT --quiet --command=\"ALTER USER \"$LAVA_DB_USER\" WITH PASSWORD '$LAVA_DB_PASSWORD'\"" || die "Failed to set database password"
 
     # Create a database for our new user, if it doesn't exist
-    if ! sudo -u postgres psql -c "SELECT datname FROM pg_database WHERE datname='$LAVA_DB_NAME'" | grep "$LAVA_DB_NAME"; then
-        sudo -u postgres createdb \
-            --port "$LAVA_DB_PORT" \
-            --locale=C.UTF-8 \
-            --encoding=UTF-8 \
-            --owner="$LAVA_DB_USER" \
-            --template=template0 \
-            --no-password \
-            "$LAVA_DB_NAME" \
-            || die "Failed to create a database"
+    if ! su postgres -c "psql -c \"SELECT datname FROM pg_database WHERE datname='$LAVA_DB_NAME'\"" | grep "$LAVA_DB_NAME"; then
+        su postgres -c "createdb --port $LAVA_DB_PORT --locale=C.UTF-8 --encoding=UTF-8 --owner=$LAVA_DB_USER --template=template0 --no-password $LAVA_DB_NAME" || die "Failed to create a database"
     fi
 }
 
