Read answers from existing config files
Check if the instance config files exist and
read the values into debconf to allow easier
migration of instances to new machines. Fix
quoting issue with DB password on master.

diff --git a/debian/lava-server.postinst b/debian/lava-server.postinst
--- a/debian/lava-server.postinst
+++ b/debian/lava-server.postinst
@@ -169,7 +169,7 @@ install_database()
     if ! su postgres -c "psql \"-c SELECT usename FROM pg_user WHERE usename='$LAVA_DB_USER'\"" | grep "$LAVA_DB_USER"; then
         su postgres -c "createuser --no-createdb --encrypted --login --no-superuser --no-createrole --no-password --port $LAVA_DB_PORT $LAVA_DB_USER"|| "Failed to create database user"
         # Set a password for our new user
-        su postgres -c "psql --port $LAVA_DB_PORT --quiet --command=\"ALTER USER \"$LAVA_DB_USER\" WITH PASSWORD '$LAVA_DB_PASSWORD'\"" || die "Failed to set database password"
+        su postgres -c "psql --port $LAVA_DB_PORT --quiet --command=\"ALTER USER \"$LAVA_DB_USER\" WITH PASSWORD '\'$LAVA_DB_PASSWORD\''\"" || die "Failed to set database password"
     fi
     # Create a database for our new user, if it doesn't exist
     if ! su postgres -c "psql -c \"SELECT datname FROM pg_database WHERE datname='$LAVA_DB_NAME'\"" | grep "$LAVA_DB_NAME"; then
