lava-test-shell: Add test result for installation
Currently lava-test-shell for each test run, first runs all the install
steps of the various tests followed by running each test one by one.
Unfortunately when the install steps for *one* of the test fails the
whole test run is aborted and no bundle are posted. Meaning that there
is no indication that anything went wrong.

Fix this by:
* Run the install steps for each test right before running the test
* saving the exit code of the install steps
* continue with the with the next step in a run if the installation fails
* Add a first synthetic test case for running the install step

Note that this has a slight semantic change in that each test will now
only run with the dependencies installed by itself and earlier tests in
a test run, rather then running with the dependencies in *all* tests of
a run.

Change-Id: I9c54cc2d642ac5ad688abe9da721c935e4babbb1

diff --git a/lava_dispatcher/lava_test_shell/distro/android/lava-test-runner b/lava_dispatcher/lava_test_shell/distro/android/lava-test-runner
--- a/lava_dispatcher/lava_test_shell/distro/android/lava-test-runner
+++ b/lava_dispatcher/lava_test_shell/distro/android/lava-test-runner
@@ -23,9 +23,10 @@ BINDIR="$LAVA_PATH/bin"
 
 hwcontext()
 {
-	mkdir -p ${RESULTSDIR}/hwcontext
-	cpuinfo=${RESULTSDIR}/hwcontext/cpuinfo.txt
-	meminfo=${RESULTSDIR}/hwcontext/meminfo.txt
+	ODIR=$1
+	mkdir -p ${ODIR}/hwcontext
+	cpuinfo=${ODIR}/hwcontext/cpuinfo.txt
+	meminfo=${ODIR}/hwcontext/meminfo.txt
 
 	[ -f ${cpuinfo} ] || cat /proc/cpuinfo > ${cpuinfo}
 	[ -f ${meminfo} ] || cat /proc/meminfo > ${meminfo}
@@ -33,9 +34,10 @@ hwcontext()
 
 swcontext()
 {
-	mkdir -p ${RESULTSDIR}/swcontext
-	build=${RESULTSDIR}/swcontext/build.txt
-	pkgs=${RESULTSDIR}/swcontext/pkgs.txt
+	ODIR=$1
+	mkdir -p ${ODIR}/swcontext
+	build=${ODIR}/swcontext/build.txt
+	pkgs=${ODIR}/swcontext/pkgs.txt
 
 	[ -f ${build} ] || getprop ro.build.display.id > ${build}
 	[ -f ${pkgs} ] || pm list packages > ${pkgs}
@@ -66,28 +68,6 @@ cleanup()
 	mv ${WORKFILE} ${WORKFILE}-${TS}
 	WORKFILE=${WORKFILE}-${TS}
 
-	echo "${PREFIX} looking for installation work in ${WORKFILE}"
-	for line in $(cat ${WORKFILE}); do
-		# we don't have "basename" on android, but this does the
-		# equivalent under mksh
-		testdir=${line%/} # trim off trailing slash iff it exists
-		test=${testdir/*\//}
-		if [ -f ${line}/install.sh ] ; then
-			echo "${PREFIX} running ${test} installer ..."
-			/system/bin/sh ${line}/install.sh
-			if [ $? -ne 0 ] ; then
-				echo "${PREFIX} ${test} installer failed, exiting"
-				hwcontext
-				swcontext
-				exit 1
-			fi
-		fi
-	done
-
-	echo "${PREFIX} save hardware/software context info..."
-	hwcontext
-	swcontext
-
 	echo "${PREFIX} looking for work in ${WORKFILE}"
 	for line in $(cat ${WORKFILE}); do
 		# we don't have "basename" on android, but this does the
@@ -98,15 +78,34 @@ cleanup()
 		odir=${RESULTSDIR}/${test}-`date +%s`
 		mkdir ${odir}
 		mkdir ${odir}/attachments/
+
+		touch ${odir}/stdout.log
+
 		cp ${line}/testdef.yaml ${odir}/
 		cp ${line}/testdef_metadata ${odir}/
 		cp ${line}/uuid ${odir}/analyzer_assigned_uuid
+
 		cp ${line}/run.sh ${odir}/attachments/
 		echo 'text/plain' > ${odir}/attachments/run.sh.mimetype
 		if [ -f ${line}/install.sh ]; then
 			cp ${line}/install.sh ${odir}/attachments/
 			echo 'text/plain' > ${odir}/attachments/install.sh.mimetype
+			echo "${PREFIX} running ${test} installer ..."
+			/system/bin/sh ${line}/install.sh
+			R=$?
+			echo ${R} > ${odir}/install_return_code
+			if [ ${R} -ne 0 ] ; then
+				echo "${PREFIX} ${test} installer failed, skippig"
+				hwcontext ${odir}
+				swcontext ${odir}
+				continue
+			fi
 		fi
+
+		echo "${PREFIX} save hardware/software context info..."
+		hwcontext ${odir}
+		swcontext ${odir}
+
 		lava-test-shell --output_dir ${odir} /system/bin/sh -e "${line}/run.sh"
 		echo "${PREFIX} ${test} exited with: `cat ${odir}/return_code`"
 	done
