Make LAVA Busybox compatible
Busybox HTTPD port configuration option added.
Fixed up lava-test-runner to use ash if bash isn't available.

Change-Id: Ia6ca2b8bb1fa10f37c598d28f692b275d6396511
Reviewed-on: https://staging.review.linaro.org/267
Reviewed-by: Antonio Terceiro <antonio.terceiro@linaro.org>

diff --git a/lava_test_shell/lava-test-runner b/lava_test_shell/lava-test-runner
--- a/lava_test_shell/lava-test-runner
+++ b/lava_test_shell/lava-test-runner
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 PREFIX="<LAVA_TEST_RUNNER>:"
 WORKFILE="/lava/lava-test-runner.conf"
@@ -84,8 +84,25 @@ for line in $(cat ${WORKFILE}); do
 	    echo 'text/plain' > ${odir}/attachments/install.sh.mimetype
 	fi
 	# run.sh includes a "read -t <timeout>" which isn't supported by dash
-	# so be sure to use bash
-	lava-test-shell --output_dir ${odir} /bin/bash -e "${line}/run.sh"
+	# so be sure to use bash (ash also works).
+
+	shell="none"
+	if [ -f /bin/bash ]; then
+		shell="/bin/bash"
+	else
+		if [ -f /bin/ash ]; then
+			shell="/bin/ash"
+		fi
+	fi
+
+	if [ $shell = "none" ]; then
+		echo "-----------------------------------------------"
+		echo "ERROR: Unable to find a usable shell. Aborting."
+		echo "-----------------------------------------------"
+		exit 1
+	fi
+
+	lava-test-shell --output_dir ${odir} ${shell} -e "${line}/run.sh"
 	echo "${PREFIX} ${test} exited with: `cat ${odir}/return_code`"
 done
 
