Fix bug #1212589 - dependencies are not installed before executing the tests.

diff --git a/lava_test_shell/lava-test-runner b/lava_test_shell/lava-test-runner
--- a/lava_test_shell/lava-test-runner
+++ b/lava_test_shell/lava-test-runner
@@ -51,15 +51,23 @@ WORKFILE=${WORKFILE}-${TS}
 echo "${PREFIX} looking for installation work in ${WORKFILE}"
 for line in $(cat ${WORKFILE}); do
 	test=`basename $line`
+        echo "${PREFIX} Check if network interface is up ..."
 	if [ -f ${line}/install.sh ] ; then
-		echo "${PREFIX} running ${test} installer ..."
-		/bin/sh ${line}/install.sh
-		if [ $? -ne 0 ] ; then
-			echo "${PREFIX} ${test} installer failed, exiting"
-			hwcontext
-			swcontext
-			exit 1
-		fi
+            /bin/ping -W1 -c1 8.8.8.8
+            if [ $? -ne 0 ] ; then
+                echo "${PREFIX} DEBUG: Dependencies will not be installed since the test image failed to bring up the network interface ..."
+		hwcontext
+		swcontext
+                exit 1
+            fi
+	    echo "${PREFIX} running ${test} installer ..."
+	    /bin/sh ${line}/install.sh
+	    if [ $? -ne 0 ] ; then
+		echo "${PREFIX} ${test} installer failed, exiting"
+		hwcontext
+		swcontext
+		exit 1
+	    fi
 	fi
 done
 
